/**
 * Language Service Sample Data
 * 
 * Provides initial sample data for language services and orders
 * to populate the system on first load.
 */

export const SAMPLE_SERVICES = [
  {
    id: 'ls-1',
    name: 'Professional English-Spanish Translation',
    description: 'High-quality translation services from English to Spanish with over 10 years of experience. Specializing in legal, medical, and business documents. Native Spanish speaker with certifications in translation.',
    languagePairs: ['en-es'],
    serviceType: 'translation',
    specializations: ['legal', 'medical', 'business'],
    pricingModel: 'per_word',
    price: 0.12,
    currency: 'USD',
    turnaroundTime: '2_days',
    turnaroundHours: 48,
    providerId: 'user-1',
    providerName: 'Maria Garcia',
    providerAvatar: 'https://ui-avatars.com/api/?name=Maria+Garcia&background=6B5B95&color=fff',
    rating: 4.8,
    reviewCount: 127,
    totalOrders: 312,
    status: 'active',
    createdAt: '2023-06-15T10:00:00Z',
    updatedAt: '2024-01-20T15:30:00Z',
  },
  {
    id: 'ls-2',
    name: 'Technical German-English Translation',
    description: 'Expert technical translation from German to English. Specialized in engineering, automotive, and software documentation. 15+ years of experience in the technical field.',
    languagePairs: ['de-en'],
    serviceType: 'translation',
    specializations: ['technical', 'software'],
    pricingModel: 'per_word',
    price: 0.15,
    currency: 'USD',
    turnaroundTime: '3_days',
    turnaroundHours: 72,
    providerId: 'provider-2',
    providerName: 'Hans Mueller',
    providerAvatar: 'https://ui-avatars.com/api/?name=Hans+Mueller&background=2D9CDB&color=fff',
    rating: 4.9,
    reviewCount: 203,
    totalOrders: 489,
    status: 'active',
    createdAt: '2023-03-10T08:00:00Z',
    updatedAt: '2024-01-18T12:00:00Z',
  },
  {
    id: 'ls-3',
    name: 'French-English Interpretation Services',
    description: 'Professional consecutive and simultaneous interpretation for business meetings, conferences, and legal proceedings. Available for in-person and remote sessions.',
    languagePairs: ['fr-en', 'en-fr'],
    serviceType: 'interpretation',
    specializations: ['business', 'legal'],
    pricingModel: 'per_hour',
    price: 75,
    currency: 'USD',
    turnaroundTime: 'custom',
    turnaroundHours: null,
    providerId: 'provider-3',
    providerName: 'Sophie Dubois',
    providerAvatar: 'https://ui-avatars.com/api/?name=Sophie+Dubois&background=9B51E0&color=fff',
    rating: 5.0,
    reviewCount: 89,
    totalOrders: 156,
    status: 'active',
    createdAt: '2023-08-20T14:00:00Z',
    updatedAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'ls-4',
    name: 'Chinese-English Website Localization',
    description: 'Complete website localization services including translation, cultural adaptation, and SEO optimization. Experience with e-commerce, SaaS, and corporate websites.',
    languagePairs: ['zh-en', 'en-zh'],
    serviceType: 'localization',
    specializations: ['website', 'marketing', 'business'],
    pricingModel: 'per_page',
    price: 120,
    currency: 'USD',
    turnaroundTime: '1_week',
    turnaroundHours: 168,
    providerId: 'provider-4',
    providerName: 'Li Wei',
    providerAvatar: 'https://ui-avatars.com/api/?name=Li+Wei&background=F2994A&color=fff',
    rating: 4.7,
    reviewCount: 64,
    totalOrders: 98,
    status: 'active',
    createdAt: '2023-09-05T11:00:00Z',
    updatedAt: '2024-01-22T16:45:00Z',
  },
  {
    id: 'ls-5',
    name: 'Japanese-English Subtitling',
    description: 'Professional video subtitling and translation services. Specialized in anime, documentaries, corporate videos, and educational content. Fast turnaround and accurate timing.',
    languagePairs: ['ja-en', 'en-ja'],
    serviceType: 'subtitling',
    specializations: ['general', 'business'],
    pricingModel: 'per_minute',
    price: 8,
    currency: 'USD',
    turnaroundTime: '3_days',
    turnaroundHours: 72,
    providerId: 'provider-5',
    providerName: 'Yuki Tanaka',
    providerAvatar: 'https://ui-avatars.com/api/?name=Yuki+Tanaka&background=27AE60&color=fff',
    rating: 4.6,
    reviewCount: 145,
    totalOrders: 267,
    status: 'active',
    createdAt: '2023-07-12T09:30:00Z',
    updatedAt: '2024-01-19T13:15:00Z',
  },
  {
    id: 'ls-6',
    name: 'Medical Spanish-English Translation',
    description: 'Certified medical translator with 12 years of experience. Specialized in patient records, clinical trials, pharmaceutical documentation, and medical research papers.',
    languagePairs: ['es-en'],
    serviceType: 'translation',
    specializations: ['medical'],
    pricingModel: 'per_word',
    price: 0.18,
    currency: 'USD',
    turnaroundTime: '2_days',
    turnaroundHours: 48,
    providerId: 'provider-6',
    providerName: 'Dr. Carlos Rodriguez',
    providerAvatar: 'https://ui-avatars.com/api/?name=Carlos+Rodriguez&background=EB5757&color=fff',
    rating: 4.9,
    reviewCount: 178,
    totalOrders: 401,
    status: 'active',
    createdAt: '2023-04-18T07:00:00Z',
    updatedAt: '2024-01-21T11:30:00Z',
  },
  {
    id: 'ls-7',
    name: 'Russian-English Legal Translation',
    description: 'Certified legal translator specializing in contracts, court documents, patents, and immigration papers. Member of the American Translators Association.',
    languagePairs: ['ru-en', 'en-ru'],
    serviceType: 'translation',
    specializations: ['legal'],
    pricingModel: 'per_page',
    price: 45,
    currency: 'USD',
    turnaroundTime: '3_days',
    turnaroundHours: 72,
    providerId: 'provider-7',
    providerName: 'Olga Petrova',
    providerAvatar: 'https://ui-avatars.com/api/?name=Olga+Petrova&background=BB6BD9&color=fff',
    rating: 5.0,
    reviewCount: 92,
    totalOrders: 187,
    status: 'active',
    createdAt: '2023-05-22T10:00:00Z',
    updatedAt: '2024-01-17T14:00:00Z',
  },
  {
    id: 'ls-8',
    name: 'Audio Transcription - Multi-Language',
    description: 'Professional audio and video transcription services in English, Spanish, French, and Portuguese. Accurate timestamps, speaker identification, and quick turnaround.',
    languagePairs: ['en-es', 'en-fr', 'en-pt'],
    serviceType: 'transcription',
    specializations: ['general', 'business'],
    pricingModel: 'per_minute',
    price: 2.5,
    currency: 'USD',
    turnaroundTime: '24_hours',
    turnaroundHours: 24,
    providerId: 'provider-8',
    providerName: 'Ana Silva',
    providerAvatar: 'https://ui-avatars.com/api/?name=Ana+Silva&background=56CCF2&color=fff',
    rating: 4.8,
    reviewCount: 234,
    totalOrders: 512,
    status: 'active',
    createdAt: '2023-06-30T12:00:00Z',
    updatedAt: '2024-01-23T10:00:00Z',
  },
  {
    id: 'ls-9',
    name: 'Korean-English Software Localization',
    description: 'Expert in software and app localization with focus on UI/UX, gaming, and mobile applications. Native Korean speaker with tech background.',
    languagePairs: ['ko-en', 'en-ko'],
    serviceType: 'localization',
    specializations: ['software', 'technical'],
    pricingModel: 'per_word',
    price: 0.14,
    currency: 'USD',
    turnaroundTime: '1_week',
    turnaroundHours: 168,
    providerId: 'provider-9',
    providerName: 'Kim Min-jun',
    providerAvatar: 'https://ui-avatars.com/api/?name=Kim+Minjun&background=6FCF97&color=fff',
    rating: 4.7,
    reviewCount: 76,
    totalOrders: 143,
    status: 'active',
    createdAt: '2023-10-08T15:00:00Z',
    updatedAt: '2024-01-16T08:30:00Z',
  },
  {
    id: 'ls-10',
    name: 'Italian-English Literary Translation',
    description: 'Award-winning literary translator specializing in novels, poetry, and creative works. Published translations of contemporary and classical Italian literature.',
    languagePairs: ['it-en', 'en-it'],
    serviceType: 'translation',
    specializations: ['literary'],
    pricingModel: 'per_word',
    price: 0.16,
    currency: 'USD',
    turnaroundTime: '2_weeks',
    turnaroundHours: 336,
    providerId: 'provider-10',
    providerName: 'Giovanni Rossi',
    providerAvatar: 'https://ui-avatars.com/api/?name=Giovanni+Rossi&background=F2C94C&color=000',
    rating: 5.0,
    reviewCount: 45,
    totalOrders: 67,
    status: 'active',
    createdAt: '2023-11-15T09:00:00Z',
    updatedAt: '2024-01-14T17:00:00Z',
  },
];

export const SAMPLE_ORDERS = [
  {
    id: 'order-1',
    serviceId: 'ls-1',
    serviceName: 'Professional English-Spanish Translation',
    providerId: 'user-1',
    providerName: 'Maria Garcia',
    customerId: 'customer-1',
    customerName: 'John Smith',
    customerEmail: 'john.smith@example.com',
    languagePair: 'en-es',
    sourceLanguage: 'en',
    targetLanguage: 'es',
    content: 'Legal contract for international business partnership...',
    wordCount: 2500,
    specialRequirements: 'Please maintain legal terminology accuracy. Deadline is critical for signing ceremony.',
    pricePerUnit: 0.12,
    totalPrice: 300,
    currency: 'USD',
    status: 'completed',
    orderDate: '2024-01-15T09:00:00Z',
    deliveryDate: '2024-01-17T17:00:00Z',
    completedDate: '2024-01-17T15:30:00Z',
    timeline: [
      { status: 'pending', date: '2024-01-15T09:00:00Z', note: 'Order received' },
      { status: 'in_progress', date: '2024-01-15T10:30:00Z', note: 'Translation started' },
      { status: 'under_review', date: '2024-01-17T14:00:00Z', note: 'Quality review in progress' },
      { status: 'completed', date: '2024-01-17T15:30:00Z', note: 'Translation completed and delivered' },
    ],
  },
  {
    id: 'order-2',
    serviceId: 'ls-2',
    serviceName: 'Technical German-English Translation',
    providerId: 'provider-2',
    providerName: 'Hans Mueller',
    customerId: 'customer-2',
    customerName: 'Emily Johnson',
    customerEmail: 'emily.j@techcorp.com',
    languagePair: 'de-en',
    sourceLanguage: 'de',
    targetLanguage: 'en',
    content: 'Technical manual for automotive engineering software...',
    wordCount: 5000,
    specialRequirements: 'Maintain technical accuracy for engineering terms. Include glossary of specialized vocabulary.',
    pricePerUnit: 0.15,
    totalPrice: 750,
    currency: 'USD',
    status: 'in_progress',
    orderDate: '2024-01-20T11:00:00Z',
    deliveryDate: '2024-01-23T17:00:00Z',
    completedDate: null,
    timeline: [
      { status: 'pending', date: '2024-01-20T11:00:00Z', note: 'Order received' },
      { status: 'in_progress', date: '2024-01-20T14:00:00Z', note: 'Translation in progress - 60% complete' },
    ],
  },
  {
    id: 'order-3',
    serviceId: 'ls-3',
    serviceName: 'French-English Interpretation Services',
    providerId: 'provider-3',
    providerName: 'Sophie Dubois',
    customerId: 'customer-3',
    customerName: 'Michael Brown',
    customerEmail: 'mbrown@globalevents.com',
    languagePair: 'fr-en',
    sourceLanguage: 'fr',
    targetLanguage: 'en',
    content: 'International business conference - 4-hour session',
    wordCount: null,
    specialRequirements: 'Need simultaneous interpretation equipment. Conference room at Downtown Convention Center.',
    pricePerUnit: 75,
    totalPrice: 300,
    currency: 'USD',
    status: 'pending',
    orderDate: '2024-01-22T08:00:00Z',
    deliveryDate: '2024-01-25T13:00:00Z',
    completedDate: null,
    timeline: [
      { status: 'pending', date: '2024-01-22T08:00:00Z', note: 'Booking request received, awaiting confirmation' },
    ],
  },
  {
    id: 'order-4',
    serviceId: 'ls-5',
    serviceName: 'Japanese-English Subtitling',
    providerId: 'provider-5',
    providerName: 'Yuki Tanaka',
    customerId: 'customer-4',
    customerName: 'Sarah Davis',
    customerEmail: 'sarah@mediaprod.com',
    languagePair: 'ja-en',
    sourceLanguage: 'ja',
    targetLanguage: 'en',
    content: 'Documentary video about Japanese culture - 45 minutes',
    wordCount: null,
    specialRequirements: 'Need subtitle file in SRT format. Ensure cultural references are properly explained.',
    pricePerUnit: 8,
    totalPrice: 360,
    currency: 'USD',
    status: 'under_review',
    orderDate: '2024-01-18T10:00:00Z',
    deliveryDate: '2024-01-21T17:00:00Z',
    completedDate: null,
    timeline: [
      { status: 'pending', date: '2024-01-18T10:00:00Z', note: 'Order received' },
      { status: 'in_progress', date: '2024-01-18T15:00:00Z', note: 'Subtitle creation started' },
      { status: 'under_review', date: '2024-01-21T14:00:00Z', note: 'Quality control and timing verification' },
    ],
  },
  {
    id: 'order-5',
    serviceId: 'ls-6',
    serviceName: 'Medical Spanish-English Translation',
    providerId: 'provider-6',
    providerName: 'Dr. Carlos Rodriguez',
    customerId: 'customer-5',
    customerName: 'Jennifer Wilson',
    customerEmail: 'jwilson@medresearch.org',
    languagePair: 'es-en',
    sourceLanguage: 'es',
    targetLanguage: 'en',
    content: 'Clinical trial documentation for pharmaceutical study...',
    wordCount: 8000,
    specialRequirements: 'HIPAA compliance required. Need certified translation with notarization.',
    pricePerUnit: 0.18,
    totalPrice: 1440,
    currency: 'USD',
    status: 'delivered',
    orderDate: '2024-01-10T07:00:00Z',
    deliveryDate: '2024-01-12T17:00:00Z',
    completedDate: '2024-01-12T16:00:00Z',
    timeline: [
      { status: 'pending', date: '2024-01-10T07:00:00Z', note: 'Order received' },
      { status: 'in_progress', date: '2024-01-10T09:00:00Z', note: 'Translation started' },
      { status: 'under_review', date: '2024-01-12T13:00:00Z', note: 'Medical terminology verification' },
      { status: 'completed', date: '2024-01-12T16:00:00Z', note: 'Translation completed' },
      { status: 'delivered', date: '2024-01-12T16:30:00Z', note: 'Delivered with certification' },
    ],
  },
];

/**
 * Initialize sample data in localStorage if not already present
 */
export function initializeSampleData() {
  // Initialize services
  const existingServices = localStorage.getItem('language_services');
  if (!existingServices) {
    localStorage.setItem('language_services', JSON.stringify(SAMPLE_SERVICES));
    console.log('[Language Services] Initialized with', SAMPLE_SERVICES.length, 'sample services');
  }

  // Initialize orders
  const existingOrders = localStorage.getItem('language_service_orders');
  if (!existingOrders) {
    localStorage.setItem('language_service_orders', JSON.stringify(SAMPLE_ORDERS));
    console.log('[Language Service Orders] Initialized with', SAMPLE_ORDERS.length, 'sample orders');
  }
}